### ISSUE TITLE
Remove Local Flag

### ISSUE THREAD

**Issue by smeubank** [getsentry/opentelemetry-demo#1]
# Bug Report

- [x] The CSS seems a bit wonky
  - Seems to be rendering better on mobile than desktop for whatever reason 
- [ ] Get rid of local flag
- [ ] Add Sentry logo as well to header image with OpenTelemetry
- [ ] Add some links to relevant docs

## Symptom

In this image we can see the following:
- language and shopping cart are rendering in the top left incorrectly
- there is the local flag on the right
- and the OpenTelemetry Image in the header could reference Sentry 

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/47563310/203748028-45fffef7-49bf-4140-97d4-67e99af3c743.png">

**What is the expected behavior?**

Renders on mobile and desktop correctly

**What is the actual behavior?**

Renders correctly
Not treated as local

## Reproduce

https://otel-demo.testa.getsentry.net/

**Comment by smeubank** [comment]
looks good now, maybe only now of interest to add some Sentry branding and get rid of the local flag

@Jesse-Box would this possibly be interesting for some artwork folks that we get something cool for this demo site?

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/47563310/203940723-feabef2b-8b2f-4988-b0ec-2470262c2ca6.png">

**Comment by mydea** [comment]
Can we close this, or is this still relevant?
