### ISSUE TITLE
Host Jaeger 

### ISSUE THREAD

**Issue by smeubank** [getsentry/opentelemetry-demo#11]
# Feature Request

Along with the Hipster Shop there is a Jaeger UI to visualize tracing and performance which folks are running locally to compare with data being sent to Sentry. Would like to have this running and easily accessible for development and testing against our fork of the Hipster shop

**Describe the solution you'd like:**

Host jaeger to display the spans and distributed tracing from our OTEL instruments services in hipster shop

**Describe alternatives you've considered.**

Everyone continues only running locally, but this is inefficient and doesn't give insight into the deployed state

**Comment by AbhiPrasad** [comment]
Jaeger should be running here: https://otel-demo.testa.getsentry.net/jaeger/ui/search
