### ISSUE TITLE
OTEL Services in Sandbox

### ISSUE THREAD

**Issue by smeubank** [getsentry/opentelemetry-demo#74]
# Feature Request

We would like for customers to be able to see services instrumented with OTel and Sentry SDKs in our [Sandbox](https://sentry.io/demo/sandbox/)

**Is your feature request related to a problem?**

Easier visibility of product value proposition

**Describe the solution you'd like:**

https://github.com/getsentry/demo/blob/master/sentrydemo/data_population.py#L1021-L1061

Include all OTel demo services, with 2 stages examples, of txns,traces, errors, and replays
- ideally releases
- moar?

## Additional Context

> This populate_generic_transaction reads data from a file and creates events with this data. So we can create a file with otel events and fill it in.

> we get transactions + errors into the sandbox by taking a JSON of the transaction and creating it in the Sandbox (not actually having code that triggers issues or transactions, here is the code that is run https://github.com/getsentry/demo/blob/master/sentrydemo/data_population.py#L1021-L1061

**Comment by smeubank** [comment]
@roggenkemper @tonyo to avoid losing things to slack threads we can move discussions here

**Comment by tonyo** [comment]
The first objective is to take an existing good-looking trace from the OTel demo org, and be able to create a few copies of the same trace in the sandbox.

Talked to @roggenkemper last week (🙏 🙏 ), so I think I now have enough inputs to implement that.

![image](https://user-images.githubusercontent.com/1120468/220303557-f69544fc-adde-477f-82b2-03c7af8304f1.png)
