### ISSUE TITLE
Tracing Problems with NextJS

### ISSUE THREAD

**Issue by smeubank** [getsentry/opentelemetry-demo#81]
Partly as a learning for NextJS SDK and to get the demo working correclty.

There issues for the NextjS project which have problems with the trace

[Example 1](https://sentry-sdks.sentry.io/issues/3850628985/?project=4503964080078848&project=4504094581063680&project=6075695&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d)

<img width="842" alt="image" src="https://user-images.githubusercontent.com/47563310/218479700-4ea6fe38-eff1-4dc9-93f8-322bc92a9f99.png">

[Example 2](https://sentry-sdks.sentry.io/issues/3927230853/?project=4503964080078848&project=4504094581063680&project=6075695&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d)

<img width="847" alt="image" src="https://user-images.githubusercontent.com/47563310/218480061-c0efb0ba-4f24-4e84-b33d-c5a620619744.png">

Can we fix them? Can we discuss why it is easy to run into these problems? Can we provide better infromation in the text we prompt the user with? These are alarming texts, user get's a lot of noise in the UI where we say something is wrong. Does it actually matter?

**Comment by smeubank** [comment]
it took me a minute to realize [this is my linked errors](https://sentry-sdks.sentry.io/performance/trace/f91b62b9aeda4455937504e1f7bce81f/?pageEnd=2023-01-05T00%3A27%3A56.742&pageStart=2023-01-04T00%3A27%3A56.742) from the trace and not error messages from Sentry failing to load a trace view

<img width="906" alt="image" src="https://user-images.githubusercontent.com/47563310/218482901-523cdd8c-1a6b-499e-8874-5ca68f631287.png">

**Comment by smeubank** [comment]
@AbhiPrasad just collecting thoughts more or less. 

We ideally fix, but would be good to give some internal dog fooding user feedback. Can we improve this experience from SDK? Issues platform UX?

**Comment by mydea** [comment]
Which of these are still relevant/correct in the current version of the SDK? cc @lforst

**Comment by lforst** [comment]
I think all of them are fixed
