### ISSUE TITLE
[go] Instrument service with Sentry

### ISSUE THREAD

**Issue by smeubank** [getsentry/opentelemetry-demo#9]
# Feature Request

Once the Go SDK work is in a first working state, lets add it to the relevant service(s) here for dogfooding and demo purposes

**Describe the solution you'd like:**

- [ ] Project(s) in Sentry SDKs org (slug: `sentry-sdk` )named with `opentelemetry-demo-SERVICE_NAME`
- [ ] add Sentry SDK to service(s)
  - [ ] [Checkout service](https://github.com/getsentry/opentelemetry-demo/tree/main/src/checkoutservice)
  - [ ] [Product Catalogue Service](https://github.com/getsentry/opentelemetry-demo/tree/main/src/productcatalogservice) 
- [ ] merge and deploy

**Describe alternatives you've considered.**
some services may be relatively simplistic, let's consider ways for relevant platforms to add beefier demo examples
- this is a nice to have to be clear

## Additional Context

this demo assists with us assessing how well the data works with the Sentry product.
- performance
- tracing
- vitals
- links to errors
- releases and so on

all will not work perfectly but gives us a vehicle by which to asses. Further this demo will become a powerful to share with users

**Comment by tonyo** [comment]
Done in https://github.com/getsentry/opentelemetry-demo/pull/56, https://github.com/getsentry/opentelemetry-demo/pull/55, and https://github.com/getsentry/opentelemetry-demo/pull/50.
